### PR TITLE
Add recipe to change sky/background color

### PR DESCRIPTION
**Pull request by sburris0**

### CODE REVIEW

**Comment by inodentry** [comment]
I don't want to call it "sky". That's misleading as it implies some sort of rendering of a "sky". This is just the background / clear color.

Remove mentions of "sky" and I'll merge it.

**Comment by sburris0** [comment]
How's "empty space"?

**Comment by inodentry** [comment]
No, it's confusing and unnecessary. Simple explanations with common or standard terminology, please.

I don't think anyone looking for this is going to be searching for "sky" or "empty space" (but they would likely search for "background", if they don't know it is called the "clear color").

There is no need to try to come up with extra things to add.

**Comment by inodentry** [comment]
Have a look at my proposal in the commit I made above. I think it makes the important information clear.

Also, IIRC, the resource must be added before the default plugins. I corrected and clarified that, too.

Also, in your original commit, you used the old pre-0.3 syntax for the default plugins.

**Comment by sburris0** [comment]
Looks good. I searched for those things but I also searched for "background color" I suppose.

**Comment by inodentry** [comment]
Yeah, I just don't want to overload the text with a bunch of different words for the same thing. Background is the typical thing people associate with this and the meaning is clear to everyone.

Merging. Thanks for your contribution.

**Pull request merged**
