### PR TITLE
Add panorbit camera

### PR DESCRIPTION
**Pull request by skairunner**

### CODE REVIEW

**Comment by inodentry** [comment]
I think this seems like the kind of thing that would be better as an actual example in the official bevy repo.

I don't want this cookbook project to steal contributions of quality examples from Bevy proper. I think your example would be a high-quality contribution to Bevy.

I intend the cookbook to be a collection of relatively short code snippets for how to do common simple tasks (so it can be useful as a reference), rather than a place for full-fledged examples/showcases. Bevy's examples directory is a much better place for such things.

If, for some reason, you can't or don't want to submit this to Bevy, I might be open to the idea of merging it here. Just let me know. :)

**Comment by skairunner** [comment]
I think it would be better if this is merged here first while a
contribution to Bevy is pending. Cart is overloaded with PRs so it might
take weeks until a new example is merged. I also feel like a pan/orbit
camera is fundamental enough to be part of Bevy core, but I'm not sure
where I'd put it...

**Comment by inodentry** [comment]
> Cart is overloaded with PRs

OK, you have a good point.

I would be OK with using the cookbook as a sort-of "incubator" for examples, to hold stuff that hasn't made its way into bevy yet (as long as the authors of such contributions are going to explore how to get the work into Bevy eventually). I just don't want my project to be to the detriment of Bevy itself.

We should put such things at the end of the cookbook and keep the short snippets at the front. I think that seems like a good rule of thumb: roughly sort the content of the cookbook by how lengthy/advanced/specific it is, so that the most widely-useful and concise stuff comes first.

EDIT: i'll come back to this PR tomorow

**Comment by skairunner** [comment]
I brought it up on discord and Cart said they think it makes more sense as
a cookbook rather than in Bevy proper. I personally don't think the pan
orbit camera is involved enough for a separate crate, either, so cookbook
it is. I will change the ordering tomorrow after work and then hopefully it
can be merged.

**Comment by skairunner** [comment]
I moved the camera to the end. It should be good to merge now.

**Comment by inodentry** [comment]
I see you made some changes to the code, too. Would have been nice to not lump multiple changes into a single git commit, but I am not gonna nitpick.

I haven't read through your code, because I don't really have the time to review it, but I will trust that you have put the care to make sure everything is good.

Thank you for your contribution!

**Comment by skairunner** [comment]
I don't actually remember changing the code... Maybe it's a mis-paste?

**Comment by inodentry** [comment]
Oh yes, I just went and took a look at it, this is clearly wrong (the immediately obvious thing is that it says `f31` instead of `f32` in multiple places, there is probably more).

OK, I guess it was careless for me to just merge this without even reading it.

Could you please go through your code and submit a fixed/correct version?

**Comment by skairunner** [comment]
I have *no* clue how that happened...

**Pull request merged**
